# Generated by Django 5.1.2 on 2024-10-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_calendarrecord_delete_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarrecord',
            name='breakfast',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarrecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='calendarrecord',
            name='dinner',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarrecord',
            name='fasting_sugar',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calendarrecord',
            name='lunch',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='calendarrecord',
            unique_together={('user', 'date')},
        ),
    ]
